version: '3'
services:
  core:
    build: ./core/
    ports:
      - "7000:7000"

  server:
    build: ./server/
    ports:
      - "8090:8090"
    environment:
      - PORT=8090
      - MONGO_DB_IP=db
      - HEXSKELL_SERVER_ADDRESS=core
      - HEXSKELL_SERVER_PORT=7000
    env_file:
      - './server.env'

  # client:
  #   build: ./client/
  #   ports:
  #     - "1234:1234"
  #   environment:
  #     - BACK_END_ADDRESS=localhost:8090
  #   env_file:
  #     - './client.env'

  db:
    image: mongo
    volumes:
      - "./db-data:/data/db"
    logging:
      driver: "none"